### ISSUE TITLE
Endpoint Enhancements (3x)

### ISSUE THREAD

**Issue by tvaroglu** [tvaroglu/spot_me_backend#62]
- GET `/users/:id/friendships` [#80](https://github.com/tvaroglu/spot_me_frontend/issues/80)
  - [x] We need an endpoint for `followees` (**followers of the current user**), which are "users that are following the current user"
    - Plan is to leverage new query param `?relationship=followee` within existing `FriendshipsController.index` action to return both user sets, so we can have `followers` and `followees` method calls that functions the same way from the current endpoint

- GET `/users/:id/events`:
  - [x] Add additional `meta` to `Events` endpoint (`gym_name: <gym_name>` and `yelp_gym_id: <yelp_gym_id>`) [#98](https://github.com/tvaroglu/spot_me_frontend/issues/98)
  - [x] Reverse sort order `desc` to be `asc` in helper methods (`Event` model) [#100](https://github.com/tvaroglu/spot_me_frontend/issues/100)

- GET `/users/:id/gym_memberships`:
  - [x] Add additional `meta` to `GymMemberships` endpoint (`address: <address>` and `address_details: <address details>`) [#89](https://github.com/tvaroglu/spot_me_frontend/issues/89)
